name: build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04
    container:
      image: nvcr.io/nvidia/pytorch:22.12-py3

    steps:
      - uses: actions/checkout@v3

        - name: environment
          run: |
            which python
            python --version

        - name: build
          run: |
            git config --global --add safe.directory /__w/DeepSpeed-Kernels/DeepSpeed-Kernels
            git submodule update --init --recursive

            ts=$(date +%s)
            DS_KERNELS_BUILD_STRING=".dev${ts}" CUDA_ARCH_LIST="80;86;89;90" python setup.py bdist_wheel
            fname=$(ls dist)
            nname=$(echo $fname | sed 's/cp[0-9]\+-cp[0-9]\+/py3-none/' | sed 's/linux/manylinux1/')
            mv "dist/$fname" "dist/$nname"
